x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  springboot:
    build:
      context: ./SpringBoot
    ports:
      - "8080:8080"

  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
#    ports:
#      - ":2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
#    ports:
#      - ':6379'
    env_file: judge0.conf
    <<: *default-logging
    restart: always

  redis-livematch:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --port 6380'
    ]
#    ports:
#      - ':6380'
    <<: *default-logging
    restart: always
    volumes:
      - redis_data:/data

  #localstack:
  #  image: localstack/localstack:latest
  #  ports:
  #    - '4566:4566'
  #    - '4510-4559:4510-4559'
  #  environment:
  #    - SERVICES=s3,sqs,lambda,iam,logs
  #    - AWS_DEFAULT_REGION=ap-southeast-1
  #    - AWS_ACCESS_KEY_ID=test
  #    - AWS_SECRET_ACCESS_KEY=test
  #  volumes:
  #    - localstack_data:/var/lib/localstack
  #    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
  localstack_data:
  redis_data:
